name: Blog CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Configuration environment
        env:
          ID_RSA: ${{secrets.id_rsa}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ID_RSA" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'Recar'
          git config --global user.email '1766241489@qq.com'
      - name: Install dependencies
        run: |
            npm i -g hexo-cli
            npm i
            npm install https://github.com/CodeFalling/hexo-asset-image --save
      - name: Deploy hexo
        run: |
          hexo g -d
      - name: send message
        run: |
           curl ${{secrets.server_url}}
